#!/bin/bash
# PBS -S /bin/bash/
# PBS <-- This is a comment, note the whitespace
# #PBS -V

#PBS -q shortq
# PBS -l walltime=168:00:00
#PBS -l nodes=8:ppn=30
#PBS -N 3DMGC
#PBS -M inchinp@my.erau.edu
#PBS -m aeb

# PBS -l mem=160000mb
#PBS -e /scratch/inchinp/magic3d/pbs_errors.out
#PBS -o /scratch/inchinp/magic3d/pbs_output.out

cd $PBS_O_WORKDIR
echo $PBS_O_WORKDIR

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/scratch/inchinp/mylib/lib:/usr/lib64

# Instead of loading modules into your profile, you can alternatively load them
# during job submission
# module load openmpi/gcc/64/1.10.3
# module load gcc/6.3.0
# module load intel/mpi/64/2017/5.239
# module load intel/compiler/64/2017/17.0.5
# module load szip/intel-compiler/2.1.1
# module load hdf5/intel-mpi/intel-compiler/1.8.19
# module load intel/mpi/64/2018/1.163
# module load intel/compiler/64/2018/18.0.1
# module load hdf5/intel-mpi/intel-compiler/1.10.3
module load hdf5/intel-mpi/intel-compiler/1.10.4
module load intel/mpi/64/2018/1.163
module load intel/compiler/64/2018/18.0.1


# module load intel/mpi/64/2018/1.163
# module load intel/compiler/64/2018/18.0.1
# module load craype-network-infiniband
# module load craype-broadwell
ulimit -s unlimited

export LD_LIBRARY_PATH
unset USERNAME
PATH=$PATH:$HOME/.local/bin:$HOME/bin
export PATH


# CPUS='cat $PBS_NODEFILE | wc -l'
echo $PBS_NODEFILE
echo $CPUS
echo $PBS_NP # PBS_NP == CPUS
echo $PBS_O_WORKDIR
echo $LD_LIBRARY_PATH
echo $PATH

# PBS_NEW_NODEFILE="/scratch/inchinp/magic/pbs_nodefile"
# /cm/shared/apps/nodefile_convert/node2host.pl $PBS_NODEFILE $PBS_NEW_NODEFILE
# PBS_NODEFILE=${PBS_NEW_NODEFILE}
# LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/scratch/inchinp/mylib/lib
# export LD_LIBRARY_PATH
# cd /scratch/inchinp/magic/
# cat $PBS_NODEFILE
# mpirun -machinefile $PBS_NODEFILE -n $PBS_NP -genv I_MPI_EAGER_THRESHOLD=128000000 ./xclawmpi
mpirun -n $PBS_NP -genv I_MPI_EAGER_THRESHOLD=128000000 ./xclawmpi
# mpirun -n $PBS_NP -genv I_MPI_EAGER_THRESHOLD=128000000 ./xclawmpi
