#!/bin/bash

 
# PBS <-- This is a comment, note the whitespace
#PBS -V
#PBS -q normalq
#PBS -l walltime=24:00:00
#PBS -l nodes=9:ppn=36
#PBS -N SNIVELY_MAGIC_3D_Test
#PBS -M snivelyj@erau.edu
#PBS -m aeb

#PBS -e /scratch/snivelyj/3D_MAGIC_2018a/pbs_errors.out
#PBS -o /scratch/snivelyj/3D_MAGIC_2018a/pbs_output.out

 
# Instead of loading modules into your profile, you can alternatively load them
# during job submission
module load intel/compiler/64/2017/17.0.5
module load intel/mpi/64/2017/5.239
ulimit -s unlimited 

CPUS='cat $PBS_NODEFILE | wc -l'
echo $PBS_NODEFILE
echo $CPUS
echo $PBS_NP # PBS_NP == CPUS
echo $PBS_O_WORKDIR
echo $LD_LIBRARY_PATH
echo $PATH

cd /scratch/snivelyj/3D_MAGIC_2018a
cat $PBS_NODEFILE
mpirun -machinefile $PBS_NODEFILE -n $PBS_NP -genv I_MPI_EAGER_THRESHOLD=32000000 ./xclawmpi
